### ISSUE TITLE
页面有遮罩时 标注被最顶层的信息遮挡辽QAQ

### ISSUE THREAD

**Issue by Rachelllllllllll** [weijian-zhu/measure.js#31]
![screenshot-10 134 2 93_8088-2022 01 11-10_58_51](https://user-images.githubusercontent.com/96721711/148873697-e22d8bf7-b435-40dd-b4b9-60fe768204f8.png)

**Comment by weijian-zhu** [comment]
https://github.com/weijian-zhu/measure.js/pull/37
