### ISSUE TITLE
气泡内显示的颜色跟 点进色板编辑时显示的颜色不符

### ISSUE THREAD

**Issue by Rachelllllllllll** [weijian-zhu/measure.js#33]
![image](https://user-images.githubusercontent.com/96721711/151332895-29c520ff-d119-49a6-bc8f-5b99d50237b8.png)

**Comment by weijian-zhu** [comment]
get



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月27日(周四) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [weijian-zhu/measure.js] 气泡内显示的颜色跟 点进色板编辑时显示的颜色不符 (Issue #33)




 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weijian-zhu** [comment]
https://github.com/weijian-zhu/measure.js/pull/37
