### ISSUE TITLE
在使用微信进行截图时，色板浮层出现在了截图遮罩层顶部，预期与整个页面一起出现在遮罩层底部才是合理的QAQ；并且使用绘图工具涂鸦时，笔触被色板遮挡，但是绘制完成后得到的图片没有被色板遮挡（图二

### ISSUE THREAD

**Issue by Rachelllllllllll** [weijian-zhu/measure.js#34]
![2251643276693_ pic](https://user-images.githubusercontent.com/96721711/151333692-3fe8da41-b625-4db0-91d7-3f444d5ba9b4.jpg)
![2241643276683_ pic](https://user-images.githubusercontent.com/96721711/151333731-b59c9136-c820-4aa3-a4ca-90e20dbd3acf.jpg)

**Comment by Rachelllllllllll** [comment]
太长了 不知道写清楚了没有hhhh

**Comment by weijian-zhu** [comment]
https://github.com/weijian-zhu/measure.js/pull/37
